markdown: rdiscount
highlighter: pygments
permalink: /blog/:year/:month/:title.html
encoding: UTF-8
name: "sifu directory"

author: "zihan05"
atom-baseurl: "https://sfmonkey.github.io"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://sfmonkey.github.io
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml